### ISSUE TITLE
TableDnD no longer working

### ISSUE THREAD

**Issue by sdespont** [wenzhixin/bootstrap-table#6111]
### Bootstraptable version(s) affected

1.20.0

### Description

When selecting a row to move it, the following error occurred : `Uncaught TypeError: this.options.onDragStop is not a function`

![image](https://user-images.githubusercontent.com/646632/165040640-1c4eda0e-7752-4fd2-8eb1-452b1bc30ae5.png)

### Example(s)

https://live.bootstrap-table.com/code/sdespont/11322

**Comment by wenzhixin** [comment]
@UtechtDustin, I think it's caused by PR #6084

**Comment by UtechtDustin** [comment]
You're right, the (empty) default functions are missing.
Will fix it in the evening.
