### ISSUE TITLE
[1.17.1] Accent Neutralise gives `Uncaught TypeError: t.normalize is not a function` if field is not a string.

### ISSUE THREAD

**Issue by marceloverdijk** [wenzhixin/bootstrap-table#5171]
**Bootstraptable version(s) affected**:
1.17.1

**Description**  
Accent Neutralise gives `Uncaught TypeError: t.normalize is not a function` if field is not a string.
Note this worked with 1.16.0

**Example**  
https://live.bootstrap-table.com/code/marceloverdijk/3918

**Possible  (optional)**  

**Additional context**  
Note this worked with the 1.16.0 extension. With 1.17.1 I just removed the extensions and bumped against this bug as search dit not work anymore with tables with Date fields.
