### ISSUE TITLE
printPageBuilder not working when table is initialized with HTML

### ISSUE THREAD

**Issue by Semptra** [wenzhixin/bootstrap-table#5976]
### Bootstraptable version(s) affected

1.19.1

### Description

Defining the `printPageBuilder ` function when bootstrap table is initialized from HTML does not affect print result (and not even called).

### Example(s)

Working example (when data is initialized with `data-url`): https://live.bootstrap-table.com/code/wenzhixin/510

For some reason, `data-show-print` attribute is not working in online editor when table is initialized in HTML (print button is not shown), so I will provide a full page HTML examples.

Not working example:

```html
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta charset="utf-8">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://unpkg.com/@fortawesome/fontawesome-free@5.12.1/css/all.min.css">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.css">

</head>

<body>
    <table id="table" data-toggle="table" data-search="true" data-show-columns="true" data-show-print="true">
        <thead>
            <tr>
                <th data-sortable="true" data-field="name">Name</th>
                <th data-sortable="true" data-field="details">Detail</th>
            </tr>
            <tbody>
                <tr>
                    <td>Name 1</td>
                    <td>Name 2</td>
                </tr>
                <tr>
                    <td>Name 3</td>
                    <td>Name 4</td>
                </tr>
                <tr>
                    <td>Name 5</td>
                    <td>Name 6</td>
                </tr>
                <tr>
                    <td>Name 7</td>
                    <td>Name 8</td>
                </tr>
            </tbody>
        </thead>
    </table>

    <script src="https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.15.4/dist/extensions/print/bootstrap-table-print.min.js"></script>

    <script type="text/javascript">
        var $table = $('#table')

        $(function () {
            $table.bootstrapTable({ 
                printPageBuilder: function(table) {
                    console.log('printPageBuilder called');
                    return 'Sample text';
                }
            })
        })
    </script>

</body>

</html>
```

Another not working example using `data-print-page-builder` attribute:

```html
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta charset="utf-8">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://unpkg.com/@fortawesome/fontawesome-free@5.12.1/css/all.min.css">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.css">

</head>

<body>
    <table id="table" data-toggle="table" data-search="true" data-show-columns="true" data-show-print="true" data-print-page-builder="printPageBuilder(table)">
        <thead>
            <tr>
                <th data-sortable="true" data-field="name">Name</th>
                <th data-sortable="true" data-field="details">Detail</th>
            </tr>
            <tbody>
                <tr>
                    <td>Name 1</td>
                    <td>Name 2</td>
                </tr>
                <tr>
                    <td>Name 3</td>
                    <td>Name 4</td>
                </tr>
                <tr>
                    <td>Name 5</td>
                    <td>Name 6</td>
                </tr>
                <tr>
                    <td>Name 7</td>
                    <td>Name 8</td>
                </tr>
            </tbody>
        </thead>
    </table>

    <script src="https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.15.4/dist/extensions/print/bootstrap-table-print.min.js"></script>

    <script type="text/javascript">
        function printPageBuilder(table) {
            console.log('printPageBuilder');
            return "Sample text";
        }
    </script>

</body>

</html>
```

Running this example results in the following error in console:

```
bootstrap-table-print.min.js:10 Uncaught TypeError: this.options.printPageBuilder.call is not a function
    at d.value (bootstrap-table-print.min.js:10)
    at HTMLButtonElement.<anonymous> (bootstrap-table-print.min.js:10)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
    at HTMLButtonElement.v.handle (jquery.min.js:2)
value @ bootstrap-table-print.min.js:10
(anonymous) @ bootstrap-table-print.min.js:10
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```

**Comment by UtechtDustin** [comment]
The issue with the `data-print-page-builder` option via html attribute  is fixed in #5977.
But i can't reproduce that `data-show-print` don't work, it's also working in the example which was provided by you.

**Comment by rmarzocchi84** [comment]
My example:

- print button works correctly on Firefox (v. 100.0.2)
- print button doesn't work on Chrome (v.101.0.4951.67)
- print button works on Vivaldi browser (5.2.2623.48) but I cannot print PDF, I can only use my predefined printer
